spring:
  application:
    name: create-post-worker

server:
  port: ${SERVER_PORT}

environment:
  mongo:
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    cluster: ${MONGO_CLUSTER}
    database: ${MONGO_DATABASE}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}